ERROR: failed to build: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
PS C:\Users\charl\dockerfile_python2> ls


    Directory: C:\Users\charl\dockerfile_python2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/18/2026  12:20 PM            151 app.py
-a----         2/18/2026  12:39 PM            349 dockefile.py
-a----         2/18/2026  12:22 PM              5 requirement.py


PS C:\Users\charl\dockerfile_python2>docker build -t a        
ERROR: docker: 'docker buildx build' requires 1 argument

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Run 'docker buildx build --help' for more information
PS C:\Users\charl\dockerfile_python2> docker build -t apps .   
[+] Building 0.1s (1/1) FINISHED                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                              0.0s
 => => transferring dockerfile: 2B                                                0.0s 
ERROR: failed to build: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
PS C:\Users\charl\dockerfile_python2> notepad dockerfile    
PS C:\Users\charl\dockerfile_python2> notepad requirement
PS C:\Users\charl\dockerfile_python2> dir


    Directory: C:\Users\charl\dockerfile_python2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/18/2026  12:20 PM            151 app.py
-a----         2/18/2026  12:39 PM            349 dockefile.py
-a----         2/18/2026  12:42 PM            349 dockerfile.txt
-a----         2/18/2026  12:22 PM              5 requirement.py
-a----         2/18/2026  12:44 PM              5 requirement.txt


PS C:\Users\charl\dockerfile_python2> docker build -t apps .
[+] Building 0.1s (1/1) FINISHED                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                              0.0s
 => => transferring dockerfile: 2B                                                0.0s 
ERROR: failed to build: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
PS C:\Users\charl\dockerfile_python2> ^C
PS C:\Users\charl\dockerfile_python2>ren dockerfile.txt Dockerfile
PS C:\Users\charl\dockerfile_python2> ren requirement.txt requirements.txt
>>
PS C:\Users\charl\dockerfile_python2> del dockefile.py
>> del requirement.py
>>
PS C:\Users\charl\dockerfile_python2> dir


    Directory: C:\Users\charl\dockerfile_python2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/18/2026  12:20 PM            151 app.py
-a----         2/18/2026  12:42 PM            349 Dockerfile
-a----         2/18/2026  12:44 PM              5 requirements.txt


PS C:\Users\charl\dockerfile_python2>docker build -t apps .              
[+] Building 0.1s (1/1) FINISHED                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                              0.0s
 => => transferring dockerfile: 388B                                              0.0s 
Dockerfile:11
--------------------
   9 |     # 3. Copy dependency file
  10 |
  11 | >>> COPY requirements.txt
  12 |
  13 |     .# 4. Install dependenciesR
--------------------
ERROR: failed to build: failed to solve: dockerfile parse error on line 11: COPY requires at least two arguments, but only one was provided. Destination could not be determined
PS C:\Users\charl\dockerfile_python2> del dockefile.py
>> del requirement.py
>>^C
PS C:\Users\charl\dockerfile_python2>notepad Dockerfile
PS C:\Users\charl\dockerfile_python2> notepad requirements.txt
PS C:\Users\charl\dockerfile_python2> docker build -t apps .  
[+] Building 25.2s (11/11) FINISHED                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                              0.0s
 => => transferring dockerfile: 337B                                              0.0s 
 => [internal] load metadata for docker.io/library/python:3.10-slim               4.7s 
 => [auth] library/python:pull token for registry-1.docker.io                     0.0s
 => [internal] load .dockerignore                                                 0.0s
 => => transferring context: 2B                                                   0.0s 
 => [1/5] FROM docker.io/library/python:3.10-slim@sha256:e508a34e5491225a76fbb9  12.2s 
 => => resolve docker.io/library/python:3.10-slim@sha256:e508a34e5491225a76fbb9e  0.1s 
 => => sha256:d0d1977db48579fff601d66e8aa7525a837b9b23aa7f8e0d 13.82MB / 13.82MB  4.5s 
 => => sha256:690eaffcf0e9a6e579bf82062d0d78590bd1bc000a309b8e76 1.29MB / 1.29MB  2.0s
 => => sha256:63ebb7511fc188c7eca8836db8cac7bc37e7d188bd4e5fc617fa0f 250B / 250B  2.0s 
 => => sha256:0c8d55a45c0dc58de60579b9cc5b708de9e7957f4591fc7d 29.78MB / 29.78MB  9.7s 
 => => extracting sha256:0c8d55a45c0dc58de60579b9cc5b708de9e7957f4591fc7de941b6  21.6s 
 => => extracting sha256:690eaffcf0e9a6e579bf82062d0d78590bd1bc000a309b8e76ff4ca  0.0s 
 => => extracting sha256:d0d1977db48579fff601d66e8aa7525a837b9b23aa7f8e0d3e1de01  1.2s 
 => => extracting sha256:63ebb7511fc188c7eca8836db8cac7bc37e7d188bd4e5fc617fa0f2  0.0s 
 => [internal] load build context                                                 0.2s 
 => => transferring context: 575B                                                 0.1s 
 => [2/5] WORKDIR /app                                                            0.2s 
 => [3/5] COPY requirements.txt .                                                 0.1s 
 => [4/5] RUN pip install --no-cache-dir -r requirements.txt                      5.0s 
 => [5/5] COPY . .                                                                0.1s 
 => exporting to image                                                            1.3s 
 => => exporting layers                                                           0.7s 
 => => exporting manifest sha256:25ad9ffb02c60ed98cd3545425702f40bfe8c14e159cf54  0.0s 
 => => exporting config sha256:d693b5c5c340115f9e26a640d1f7351d56d3aa39b064be873  0.0s 
 => => exporting attestation manifest sha256:d1e79d1686ec03089606ce89b211f9edf1d  0.0s 
 => => exporting manifest list sha256:24d3458f93ccdd927083551ac07a485c26e8475717  0.0s 
 => => naming to docker.io/library/apps:latest                                    0.0s 
 => => unpacking to docker.io/library/apps:latest                                 0.4s 
PS C:\Users\charl\dockerfile_python2> docker images
REPOSITORY                                TAG                                          
                                 IMAGE ID       CREATED          SIZE
apps                                      latest                                       
                                 24d3458f93cc   56 seconds ago   200MB
mongo                                     latest                                       
                                 6f55a078e025   2 weeks ago      1.27GB
charlenn/ap1                              v1.1                                         
                                 25109184c71b   3 weeks ago      13MB
charlenn/apl                              v1.1                                         
                                 25109184c71b   3 weeks ago      13MB
alpine                                    latest                                       
                                 25109184c71b   3 weeks ago      13MB
mysql                                     latest                                       
                                 6b18d01fb632   3 weeks ago      1.25GB
redis                                     latest                                       
                                 73dad4271642   5 weeks ago      202MB
httpd                                     latest                                       
                                 dd178595edd6   5 weeks ago      175MB
smart-log-analyzer-log-analyzer           latest                                       
                                 f3b0c27a5469   2 months ago     671MB
devops_project_extended-app               latest                                       
                                 d6c03eec565b   2 months ago     1.3GB
mysql                                     8.0                                  
                                 0275a35e79c6   2 months ago     1.06GB
redis                                     7                                            
                                 483eaf69e400   3 months ago     173MB
nginx                                     alpine                                       
                                 b3c656d55d7a   3 months ago     79.8MB
<none>                                    <none>                                       
                                 569c4128dfa6   3 months ago     1.27GB
ubuntu                                    latest                                       
                                 c35e29c94501   4 months ago     117MB
python                                    alpine                                       
                                 8373231e1e90   4 months ago     71.9MB
<none>                                    <none>                                       
                                 4b7ce07002c6   4 months ago     12.8MB
docker/desktop-kubernetes                 kubernetes-v1.34.1-cni-v1.7.1-critools-v1.33.0-cri-dockerd-v0.3.20-1-debian   12d6673564e0   5 months ago     591MB
registry.k8s.io/kube-scheduler            v1.34.1                                      
                                 6e9fbc4e25a5   5 months ago     73.5MB
registry.k8s.io/kube-controller-manager   v1.34.1                                      
                                 2bf47c1b01f5   5 months ago     101MB
registry.k8s.io/kube-apiserverv1.34.1                                      
                                 b9d7c117f8ac   5 months ago     118MB
registry.k8s.io/kube-proxy                v1.34.1                                      
                                 913cc83ca0b5   5 months ago     102MB
registry.k8s.io/etcd                      3.6.4-0                                      
                                 e36c08168342   6 months ago     273MB
registry.k8s.io/pause                     3.10.1                                       
                                 278fb9dbcca9   8 months ago     1.06MB
registry.k8s.io/coredns/coredns           v1.12.1                                      
                       e8c262566636   10 months ago    101MB
registry.k8s.io/pause                     3.10                                         
                                 ee6521f290b2   21 months ago    1.06MB
PS C:\Users\charl\dockerfile_python2> docker run -d --name p1 python1
Unable to find image 'python1:latest' locally
docker: Error response from daemon: pull access denied for python1, repository does not exist or may require 'docker login'

Run 'docker run --help' for more information
PS C:\Users\charl\dockerfile_python2> docker login            
Authenticating with existing credentials... [Username: charlenn]

i Info → To login with a different account, run 'docker logout' followed by 'docker login'


Login Succeeded
PS C:\Users\charl\dockerfile_python2> docker run -d --name a1 python1
Unable to find image 'python1:latest' locally
docker: Error response from daemon: pull access denied for python1, repository does not exist or may require 'docker login'

Run 'docker run --help' for more information
PS C:\Users\charl\dockerfile_python2>^C
PS C:\Users\charl\dockerfile_python2> docker run -d --name p1 apps   
f626417bd5c8f239b944ba486d8068e37d4cedbc51d0c335322d89d71ca8201a
f626417bd5c8f239b944ba486d8068e37d4cedbc51d0c335322d89d71ca8201a
PS C:\Users\charl\dockerfile_python2> docker run -d --name p1 -p apps 500/: - python1^CPS C:\Users\charl\dockerfile_python2> docker run -d --name p1 -p 5000:5000 apps
>>
docker: Error response from daemon: Conflict. The container name "/p1" is already in use by container "f626417bd5c8f239b944ba486d8068e37d4cedbc51d0c335322d89d71ca8201a". You have to remove (or rename) that container to be able to reuse that name.

Run 'docker run --help' for more information
PS C:\Users\charl\dockerfile_python2> ^C
PS C:\Users\charl\dockerfile_python2>
